% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

Assignment 1 Experimental Design and Data Analysis Group 57 - Layla
Nolte, Jensen Valkenhoff, Richard Pereira e Silva

\hypertarget{exercise-1a-seeded-clouds}{%
\subsection{Exercise 1a) Seeded
clouds}\label{exercise-1a-seeded-clouds}}

We compare rainfall from \textbf{two independent samples} (26 seeded vs
26 unseeded clouds). The data are \textbf{not paired}, since different
clouds were assigned to treatment and control groups.

The research question is whether \textbf{seeding increases rainfall}, so
we mainly consider the one-sided alternative
\(H_1:\mu_{\text{seeded}}>\mu_{\text{unseeded}}\), but we also report
two-sided p-values.

\includegraphics{template_assign_edda_files/figure-latex/ex1a_all-1.pdf}

\begin{verbatim}
##           Test p..two.sided. p..seeded...unseeded.
## 1 Welch t-test        0.0538               0.02688
## 2 Mann–Whitney        0.0138               0.00692
## 3      KS test        0.0177                    NA
\end{verbatim}

\begin{verbatim}
## 
## Conclusion (alpha = 0.05):
\end{verbatim}

\begin{verbatim}
## - Welch t-test: two-sided p = 0.0538; one-sided (seeded > unseeded) p = 0.0269.
\end{verbatim}

\begin{verbatim}
## - Mann–Whitney: two-sided p = 0.0138; one-sided p = 0.0069.
\end{verbatim}

\begin{verbatim}
## - KS test (two-sided): p = 0.0177.
\end{verbatim}

\begin{verbatim}
## 
## Interpretation:
\end{verbatim}

\begin{verbatim}
## Rainfall is highly skewed with extreme values, so the t-test assumptions are questionable.
\end{verbatim}

\begin{verbatim}
## Nonparametric tests (Mann–Whitney and KS) indicate a significant difference between groups.
\end{verbatim}

\begin{verbatim}
## Because assignment to seeded/unseeded clouds was randomized, a permutation test is applicable and valid.
\end{verbatim}

Applicability.

Welch t-test targets means and is sensitive to skewness/outliers.

Mann--Whitney compares location (often interpreted as median shift under
assumptions).

KS compares entire distributions. A permutation test is applicable
because treatment assignment was randomized.

\hypertarget{exercise-1b-transformations-of-rainfall}{%
\subsection{Exercise 1b) Transformations of
rainfall}\label{exercise-1b-transformations-of-rainfall}}

To reduce skewness and stabilize variance, we repeat the analysis using
the square root and the fourth root (sqrt of sqrt) transformations of
rainfall.

\includegraphics{template_assign_edda_files/figure-latex/ex1b_transformations-1.pdf}

\begin{verbatim}
##   Transformation Welch.p Mann.Whitney.p KS..two.sided..p
## 1           Sqrt 0.00978        0.00692           0.0177
## 2    Fourth-root 0.00620        0.00692           0.0177
\end{verbatim}

The square-root transformation reduces skewness compared to the original
data, and the fourth-root transformation improves symmetry even further,
as seen in the QQ-plots.

After transformation, the Welch t-test becomes more reliable because the
normality assumption is better satisfied. The significance levels remain
similar, and the evidence that seeded clouds produce more rainfall
persists.

The nonparametric tests (Mann--Whitney and KS) are largely unaffected by
transformation, since they do not rely on normality assumptions.

Overall, the conclusion from Exercise 1a remains unchanged: there is
evidence that seeding increases rainfall.

\hypertarget{exercise-1c-testing-population-mean}{%
\subsection{Exercise 1c) Testing Population
Mean}\label{exercise-1c-testing-population-mean}}

\begin{verbatim}
## [1] 3.88
\end{verbatim}

\begin{verbatim}
## [1] 20
\end{verbatim}

\begin{verbatim}
## 
##  Exact binomial test
## 
## data:  20 and 26
## number of successes = 20, number of trials = 26, p-value = 0.005
## alternative hypothesis: true probability of success is greater than 0.5
## 95 percent confidence interval:
##  0.595 1.000
## sample estimates:
## probability of success 
##                  0.769
\end{verbatim}

\begin{verbatim}
## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  t1
## V = 280, p-value = 0.004
## alternative hypothesis: true location is greater than 3
\end{verbatim}

\begin{verbatim}
##   Transformation  Mu...3 Mu...4 M...3.5
## 1        P-Value 0.00242  0.663  0.0973
\end{verbatim}

The true mean of t1 is 3.88. The t-tests applied indicate that by
rejecting that t1 mean is greater than 4 and failing to reject that it
is greater than 3. The binomial test corroborates that. We can use the
wilcoxon sign test rank to achieve the same result as shown above,
Wilcoxon test doesn't rule out m \textgreater{} 3 either.

\hypertarget{exercise-1d-using-median-as-bootstrap-statistic}{%
\subsection{Exercise 1d) Using Median as Bootstrap
Statistic}\label{exercise-1d-using-median-as-bootstrap-statistic}}

\begin{verbatim}
## [1] 272
\end{verbatim}

\begin{verbatim}
## [1] 612
\end{verbatim}

\begin{verbatim}
## 97.5%  2.5% 
##   566   767
\end{verbatim}

\begin{verbatim}
## [1] 0.006
\end{verbatim}

\includegraphics{template_assign_edda_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{verbatim}
## 
##  Asymptotic one-sample Kolmogorov-Smirnov test
## 
## data:  jitter(Tstar)
## D = 1, p-value <2e-16
## alternative hypothesis: two-sided
\end{verbatim}

Using the Central Limit Theorem we found a mean of 442 with a 95\% CI of
{[}272,612{]}. Using the boostrap method with median as statistic we
ruled out that the data is following a exponential distribution by first
assuming that it was exponential and then testing it with the bootstrap
test and Kolmogorov-Smirnov test. Both tests returned very small
p-values indicating that the original distribution is not exponential.
That is also clear looking at the histogram above.

\hypertarget{exercise-1e-median-and-fraction-tests-seeded-clouds}{%
\subsection{Exercise 1e) Median and fraction tests (seeded
clouds)}\label{exercise-1e-median-and-fraction-tests-seeded-clouds}}

We consider only the seeded sample (\(n = 26\)). Because rainfall is
highly skewed, we use exact binomial tests.

\hypertarget{i-test-whether-the-median-precipitation-is-less-than-300}{%
\subsubsection{(i) Test whether the median precipitation is less than
300}\label{i-test-whether-the-median-precipitation-is-less-than-300}}

We perform a sign test:

\[
H_0: \text{median} = 300
\qquad \text{vs} \qquad
H_1: \text{median} < 300.
\]

Out of 26 observations, 17 are below 300. The exact binomial test yields
\(p = 0.084\).

\textbf{Conclusion (\(\alpha = 0.05\)).} Since \(p = 0.084 > 0.05\), we
do not reject \(H_0\).\\
There is insufficient evidence that the median precipitation of seeded
clouds is less than 300.

\hypertarget{ii-test-whether-the-fraction-with-precipitation-30-is-at-most-25}{%
\subsubsection{(ii) Test whether the fraction with precipitation
\textless{} 30 is at most
25\%}\label{ii-test-whether-the-fraction-with-precipitation-30-is-at-most-25}}

Let \(p = P(X < 30)\). We test:

\[
H_0: p \le 0.25
\qquad \text{vs} \qquad
H_1: p > 0.25.
\]

We observe 3 out of 26 clouds with precipitation below 30, so
\(\hat p = 3/26 = 0.115\). The exact binomial test yields \(p = 0.974\),
with a 95\% confidence interval for \(p\) equal to \([0.024,\, 0.302]\).

\textbf{Conclusion (\(\alpha = 0.05\)).} Since \(p = 0.974 > 0.05\), we
do not reject \(H_0\).\\
The data are consistent with the fraction of seeded clouds with
precipitation below 30 being at most 25\%.

\hypertarget{exercise-2}{%
\subsection{Exercise 2)}\label{exercise-2}}

The second exercise is an analysis of how three different types of diet
influence the weight loss among a population with N=78. Each person
followed a specific diet during 6 weeks and the weight before and after
this time period are measured. The considered dataset is
\texttt{diet.txt}, which contains 7 variables for each member of the
population. \texttt{preweight} here describes the initial weight and
\texttt{weight6weeks} the after taking the diet for 6 weeks. An
additional variable \texttt{weight.loss} is added to the data to perform
paired sample testing during the exercise. The resulting dataset is as
follows:

\begin{verbatim}
##                                                                             
## 1 function (..., list = character(), package = NULL, lib.loc = NULL,        
## 2     verbose = getOption("verbose"), envir = .GlobalEnv, overwrite = TRUE) 
## 3 {                                                                         
## 4     fileExt <- function(x) {                                              
## 5         db <- grepl("\\\\.[^.]+\\\\.(gz|bz2|xz)$", x)                     
## 6         ans <- sub(".*\\\\.", "", x)
\end{verbatim}

\hypertarget{exercise-2a}{%
\subsection{Exercise 2a)}\label{exercise-2a}}

This section contains the \emph{informative graphical summary of the
effect of diet on weight loss}. Since the data is measured for the same
individuals before and after six weeks on the diet, the data are paired.
The following assumptions have to be met before performing a paired
t-test: independency of pairs, normality of weight loss, and the absence
of extreme outliers. The considered response variable is
\texttt{data\$weight\_loss} for this sub-exercise.

\textbf{a)} The first assumption is met by the definition of the
dataset, since the measurements are all indepent of each other.

\textbf{b)} The second assumption can be checked by a QQ-plot. The red
line represents the reference line under normality. Since the majority
of the data points lie close to this line, there is strong evidence that
normality can be assumed. Since this is the case in the figure, it is
reasonable that the data is normally distributed.

\textbf{c)} A boxplot is created to visually check whether the data
contains outliers or not. The boxplot shows the median, interquartile
range, and potential extreme values. To asses the amount of outliers
numerically, the command \texttt{boxplot.stats(weight\_loss)\$out} is
used, which gave \texttt{numeric(0)} as output, meaning that the data
does not contain any outliers.

\includegraphics{template_assign_edda_files/figure-latex/normality assumptions-1.pdf}

To test claim that \emph{the diet affects the weight loss}, a paired
t-test was performed with \texttt{data\$weight\_loss} as response
variable. The hypotheses are:

\begin{itemize}
\tightlist
\item
  \textbf{H0:}The mean weight loss is equal to zero. \((\mu_x = 0)\)
\item
  \textbf{H1:} The mean weight loss is not equal to zero.
  \((\mu_x \neq 0)\) The paired t-test resulted in a p-value of 1.17 ×
  10⁻²¹, which is far below the significance level of \(\alpha = 0.05\).
  Consequently, the null hypothesis that there is no difference between
  \texttt{preweight} and \texttt{weight6weeks} is rejected, such that
  \emph{HA:} The mean weight loss is not equal to zero, is accepted
  \(\mu_x \neq 0\). In other words, there is an observed difference
  between the variables \texttt{preweight} and \texttt{weight6weeks} and
  the mean difference is 3.84, implying that an individual loses 3.84 kg
  weight on average by taking a diet according to the data.
\end{itemize}

\begin{verbatim}
## 
##  Paired t-test
## 
## data:  preweight and weight6weeks
## t = 13, df = 77, p-value <2e-16
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  3.27 4.42
## sample estimates:
## mean difference 
##            3.84
\end{verbatim}

\hypertarget{exercise-2b}{%
\subsection{exercise 2b}\label{exercise-2b}}

This section investigates whether weight loss differs between the three
diet groups. The response variable is the \texttt{weight\_loss},
computed as the difference between \texttt{preweight} and
\texttt{weight6weeks}. Since the factor diet contains three independent
groups, a one-way ANOVA is used to test whether the mean weight loss is
equal across diets. The hypotheses are:

\begin{itemize}
\tightlist
\item
  \textbf{H0:} The mean weight loss is equal across all diet groups.
  \((\mu_{1} = \mu_{2} = \mu_{3})\)
\item
  \textbf{H1:} At least one diet group has a different mean weight loss.
  A boxplot is created to compare the distribution of weight loss across
  the three diet groups. The differences of the mean and the spread
  among the groups give a visual indication of whether the diets may
  lead to different outcomes.
\end{itemize}

\includegraphics{template_assign_edda_files/figure-latex/boxplot among diet groups-1.pdf}

A one-way ANOVA is performed to test whether the mean weight loss
differs between diet group. The results of the analysis are summarized
in the table below, displaying that the null hypothesis is rejected
since \texttt{p\ =\ 0.003\ \textless{}\ 0.05}. This means that
`\textbf{H1:} At least one diet group has a different mean weight loss.'
is true.

\begin{verbatim}
##             Df Sum Sq Mean Sq F value Pr(>F)   
## diet         2     71    35.5     6.2 0.0032 **
## Residuals   75    430     5.7                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

To determine whether every separate diet leads to weight loss, three
one-sample t-test were performed on each diet group, with the following
hypotheses:

\begin{itemize}
\tightlist
\item
  \textbf{H0:} Mean weight loss = 0.
\item
  \textbf{H1:} Mean weight loss \textgreater{} 0.
\end{itemize}

Again, \texttt{weight\_loss} is the computed response variable and is
used as before. To perform the one sample t-tests, see Section 2a to see
which conditions have to be met to perform a proper t-test. The
partitions of group 2 and group 3 seem to be suitable for a one-sample
t-test, as the majority of the datapoints lie around the linear line and
there are no extreme outliers. Although the first dataset shows two
potential outliers in both the Q-Q plot and the boxplot, the overall
distribution does differ much from normality, suggestingn that a t-test
can be used in this.

\includegraphics{template_assign_edda_files/figure-latex/qqplots-1.pdf}
\includegraphics{template_assign_edda_files/figure-latex/qqplots-2.pdf}
According to the performed t-test, every outcome implies that
\textbf{H0} is rejected since p \textless{} 0.05, such that
`\textbf{H1:} Mean weight loss \textgreater{} 0.' is accepted for every
diet group. \((\mu_1, \mu_2, \mu_3) \approx (2.516,3.026,5.148)\),
suggesting that diet group 3 has the highest observed weight loss with a
mean value of \(\mu_3 \approx 5.148\).

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  data$weight_loss[data$diet == 1]
## t = 7, df = 23, p-value = 1e-07
## alternative hypothesis: true mean is greater than 0
## 95 percent confidence interval:
##  2.52  Inf
## sample estimates:
## mean of x 
##       3.3
\end{verbatim}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  data$weight_loss[data$diet == 2]
## t = 6, df = 26, p-value = 7e-07
## alternative hypothesis: true mean is greater than 0
## 95 percent confidence interval:
##  2.2 Inf
## sample estimates:
## mean of x 
##      3.03
\end{verbatim}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  data$weight_loss[data$diet == 3]
## t = 11, df = 26, p-value = 1e-11
## alternative hypothesis: true mean is greater than 0
## 95 percent confidence interval:
##  4.36  Inf
## sample estimates:
## mean of x 
##      5.15
\end{verbatim}

\hypertarget{exercise-2c}{%
\subsection{exercise 2C)}\label{exercise-2c}}

Question 2C investigates whether weight loss depends on diet, gender,
and their interaction. The response variable is \texttt{weight\_loss},
computed as the difference between \texttt{preweight} and
\texttt{weight6weeks}. Since we have \textbf{two categorical factors}
(diet with three groups, and gender with two groups), a \textbf{two-way
ANOVA} is used.

\hypertarget{hypotheses}{%
\subsubsection{Hypotheses}\label{hypotheses}}

We test three effects: \textbf{diet}, \textbf{gender}, and their
\textbf{interaction}.

\hypertarget{main-effect-of-diet}{%
\paragraph{Main effect of Diet}\label{main-effect-of-diet}}

\begin{itemize}
\tightlist
\item
  \textbf{H0:} The mean weight loss is equal across all diet groups.
  \((\mu_{1} = \mu_{2} = \mu_{3})\)
\item
  \textbf{H1:} At least one diet group has a different mean weight loss.
\end{itemize}

\hypertarget{main-effect-of-gender}{%
\paragraph{Main effect of Gender}\label{main-effect-of-gender}}

\begin{itemize}
\tightlist
\item
  \textbf{H0:} The mean weight loss is equal for both genders.
  \((\mu_M = \mu_F)\)
\item
  \textbf{H1:} The mean weight loss differs between genders.
  \((\mu_M \neq \mu_F)\)
\end{itemize}

\hypertarget{interaction-effect-diet-gender}{%
\paragraph{Interaction effect (Diet ×
Gender)}\label{interaction-effect-diet-gender}}

\begin{itemize}
\tightlist
\item
  \textbf{H0:} There is no interaction between diet and gender (the
  effect of diet is the same for both genders).
\item
  \textbf{H1:} There is an interaction between diet and gender (the
  effect of diet depends on gender).
\end{itemize}

\begin{verbatim}
##   diet weight_loss
## 1    1        3.30
## 2    2        3.03
## 3    3        5.15
\end{verbatim}

\begin{verbatim}
##   gender weight_loss
## 1      0        3.89
## 2      1        4.02
\end{verbatim}

The below figures are used to give a visual indication of the effects
and the interactions. The boxplot for weight loss by gender indicates
that although the spread among men is higher than for women, the average
mean weight loss is almost equal \(\mu_m = 3.893 \land \mu_f = 4.015)\).
For the diet groups, we clearly observe visually that the third diet
group (purple) causes a higher weight loss \((\mu_3 = 5.148)\) than the
first and the second group \((\mu_1 = 3.300 \land \mu_2 = 3.026)\).
\includegraphics{template_assign_edda_files/figure-latex/visual indication boxplots Two-way ANOVA-1.pdf}

\begin{verbatim}
##   diet gender weight_loss
## 1    1      0        3.05
## 2    2      0        2.61
## 3    3      0        5.88
## 4    1      1        3.65
## 5    2      1        4.11
## 6    3      1        4.23
\end{verbatim}

The interaction plots below show that the effect of diet on weight loss
differs between genders. In the table above, 0 is translated to m (men)
and 1 to f (female). To support this interpretation, we consider the
cell means (interaction means) for each combination of diet group and
gender. For women, the mean weight loss
equals\((\mu_{1,m},\mu_{2,m}, \mu_{3,m}) = (3.05,2.61,5.88).\) This
indicates that diet 3 leads to a clearly higher mean weight loss
compared with diets 1 and 2.

For womenn, the mean weight loss equals
\((\mu_{1,f},\mu_{2,f},\mu_{3,f})= (3.65,4.11,4.23)\). Here, the mean
weight loss is more equally divided across the three diets. This
suggests that the diet effect is more pronounced for men, especially for
diet 3.

\includegraphics{template_assign_edda_files/figure-latex/interaction plots-1.pdf}
\includegraphics{template_assign_edda_files/figure-latex/interaction plots-2.pdf}

Two-way ANOVA was perfofrmed to determine the effects of diet, gender,
and their interaction on weight loss. There was a significant main
effect of diet, \(F( = 5.63\), \(p = 0.005\), indicating that mean
weight loss differs between the three diet groups. The main effect of
gender was not significant, \(F = 0.03\), \(p = 0.860\), suggesting that
overall weight loss does not differ between men and women. Importantly,
a significant interaction between diet and gender was
found,\(F = 3.15\), \(p = 0.049\). This is evidence that the effect of
diet on weight loss depends on gender.

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: weight_loss
##                           Df Sum Sq Mean Sq F value Pr(>F)   
## diet_factor                2     61   30.26    5.63 0.0054 **
## gender_factor              1      0    0.17    0.03 0.8599   
## diet_factor:gender_factor  2     34   16.95    3.15 0.0488 * 
## Residuals                 70    376    5.38                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{exercise-2d}{%
\subsection{exercise 2D}\label{exercise-2d}}

For exercise 2D, we included the variables gender, height and age to
investigate whether these covariates influence weight loss. The models
used are linear models (\texttt{lm}), which fits linear regression
models by least squares. We use an ANCOVA (analysis of covariance) model
because both categorical (\texttt{diet\ group} \& \texttt{gender} and
continuous variables (\texttt{height} \& \texttt{age}) are included in
this case.

The four scatterplots of \texttt{weight\_loss} against \texttt{age} and
\texttt{height}, are categorized by either gender or diet group. None of
the scatterplots shows a clear linear relationship, suggesting that both
\texttt{height} and \texttt{age} do not influence weight loss, neither
show crossover effects with \texttt{diet} and \texttt{age}. These
observations will be formally tested using regression analysis. Only the
interaction \texttt{diet*gender} will be analyzed in this part, since
the interaction is significant according to exc 2C.

\includegraphics{template_assign_edda_files/figure-latex/unnamed-chunk-4-1.pdf}

An ANOVA test is performed on the linear model including diet, gender,
height and age. The ANOVA table shows that diet has a significant effect
on \texttt{weight\_loss} (p \textless{} 0.05), but \texttt{gender},
\texttt{height} and \texttt{age} are not statistically significant (p
\textgreater{} 0.05). This means that there is no evidence that these
variables independently influence \texttt{weight\_loss} in the linear
model.

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: weight_loss
##           Df Sum Sq Mean Sq F value Pr(>F)   
## diet       2     61   30.26    5.18  0.008 **
## gender     1      0    0.17    0.03  0.866   
## height     1      1    0.78    0.13  0.715   
## age        1      0    0.43    0.07  0.786   
## Residuals 70    409    5.84                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

We included the interaction between diet and gender as well to
investigate whether the effect of diet differs between genders. The
interaction term diet \textasciitilde{} gender is statistically
significant (p = 0.048 \textless{} 0.05), which means that the
interaction between gender and diet has effect on \texttt{weight\_loss}.
This means that the model fit is improved compared to the first model.
The remaining variables (excluding diet), do not show a significant
effect on the model fit.

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: weight_loss
##             Df Sum Sq Mean Sq F value Pr(>F)   
## diet         2     61   30.26    5.50 0.0061 **
## gender       1      0    0.17    0.03 0.8615   
## height       1      1    0.78    0.14 0.7069   
## age          1      0    0.43    0.08 0.7800   
## diet:gender  2     35   17.48    3.18 0.0479 * 
## Residuals   68    374    5.50                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

To investigate which model should be chosen, an additional ANOVA test is
performed on the two models. Since p = 0.048 \textless{} 0.05,
\textbf{H0} is rejected, so we can conclude that the interaction has
effect on the model. This means that we should rather use
\texttt{model\_int} for, since including the interaction diet * gender
improves the model according to the ANOVA test.

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: weight_loss ~ diet + gender + height + age
## Model 2: weight_loss ~ diet * gender + height + age
##   Res.Df RSS Df Sum of Sq    F Pr(>F)  
## 1     70 409                           
## 2     68 374  2        35 3.18  0.048 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{exercise-2e}{%
\subsection{exercise 2E}\label{exercise-2e}}

For the selected model from Exercise 2D, \[
\text{weight\_loss} \sim \text{diet} * \text{gender} + \text{height} + \text{age},
\] predictions were computed for an average person (age and height set
to their sample means). Here, gender = 0 denotes men and gender = 1
denotes women.

\begin{verbatim}
##   diet gender  age height  fit  lwr  upr
## 3    3      0 39.2    171 5.76 4.47 7.05
## 5    2      1 39.2    171 4.30 2.70 5.90
## 6    3      1 39.2    171 4.24 2.88 5.60
## 4    1      1 39.2    171 3.63 2.14 5.12
## 1    1      0 39.2    171 3.09 1.83 4.34
## 2    2      0 39.2    171 2.56 1.29 3.82
\end{verbatim}

\end{document}
